### PR TITLE
Expiration parameter

### PR DESCRIPTION
**Pull request by klische**
In service of https://github.com/ProtonMail/gopenpgp/issues/54

### CODE REVIEW

**Comment by twiss** [comment]
Hey :wave: Thanks for your PRs! :+1:

Some people use `ProtonMail/crypto` directly, so we want to keep a stable API here as well. Could you, instead of adding a parameter to `NewEntity`, add a field to `packet.Config`?

**Comment by twiss** [comment]
Hey @klische :wave: Gentle reminder, are you still interested in, and do you still have time for, updating this PR?

**Comment by trishankatdatadog** [comment]
My PRs #60 and #64 should fix this. Once the latter is closed, we should close this one, too.

**Comment by trishankatdatadog** [comment]
@twiss We can probably close this now thanks to #64?

**Pull request closed without merging**
