### PR TITLE
Fix for KeyID digest generation

### PR DESCRIPTION
**Pull request by L11R**
Original issue:
https://github.com/ProtonMail/gopenpgp/issues/10
Issue explanation:
https://github.com/ProtonMail/gopenpgp/issues/10#issuecomment-498066306

### CODE REVIEW

**Comment by twiss** [comment]
Hi @L11R! Thanks for catching this, and for investigating. The PR looks good to me. I'm just trying to figure out why the tests failed in Go 1.10, do you have any ideas?

**Comment by L11R** [comment]
I guess your test are just not fully reproducible from time to time. Restart might help.

**Comment by L11R** [comment]
@twiss how soon you will merge it? I think it's sorta critical issue and should be fixed ASAP, would be nice also prepare new GopenPGP release with new `replace` directive.

**Comment by twiss** [comment]
@L11R this MPI code is not quite correct when the MPI has leading zeros. That's also what caused the failing test - there's a small chance of producing a broken MPI. Give me a moment, I'll push a fix.

**Comment by L11R** [comment]
Thanks, got it, will wait.

**Pull request merged**
